name = "haze-stdlib"
version = "0.0.0"
description = "The default standard library for Haze"
license = "MIT"
authors = []
type = "lib"

# [dependencies]
# serde = "1.0.193"
# haze-utils = "0.2.4"

# [build]
# output = "build/"
# optimize = true

# [tool.haze]
# strict = true
# warnings_as_errors = false

[compiler]
flags = ["-D_XOPEN_SOURCE=500", "-H"]

[linker]
# flags = ["-lm", "-lGL", "-lpthread"]
flags = ["-lunwind", "-ldl", "-lc"]