
name = "test"
version = "0.1.0"
description = "A sample Haze project"
license = "MIT"
authors = []
src = "test"
# src = "compiler/haze-parser/src"
type = "exe"
# std = "none"


# [build]
# output = "build/"
# optimize = true

[scripts]
build = "haze build"
run = "haze run"
test = "haze test"

# [tool.haze]
# strict = true
# warnings_as_errors = false

[dependencies]
glfw = { path = "./glfw" }
math = { path = "./math" }
gl = { path = "./gl" }
wgpu = { path = "./wgpu" }
glfw_wgpu = { path = "./glfw_wgpu" }
# gl = { path = "./gl" }
# glDraw = { path = "./glDraw" }
# ember = { path = "./ember" }

[linker]
# flags = ["-lm", "-lglfw3"]