name = "glfw"
version = "1.0.0"
description = "GLFW support for Haze"
license = "MIT"
authors = ["HerrNamenlos123"]
type = "lib"
# src = "."

[scripts.linux]
prebuild = { command = "$HAZE_MODULE_SOURCE_DIR/build-linux.sh", depends = "./**/*" }

[scripts.win32]
prebuild = { command = "call \"%HAZE_MODULE_SOURCE_DIR%/build-win.bat\"", depends = "./**/*" }

[interface.compiler.linux]
defines = ["_GLFW_X11", "_GLFW_WAYLAND"]

[interface.compiler.win32]
defines = ["_GLFW_WIN32"]

[linker]
flags = ["-lglfw3"]

[linker.linux]
flags = ["-lm", "-lGL", "-lpthread"]

[linker.win32]
flags = ["-luser32", "-lgdi32", "-lshell32"]