name = "glfw"
version = "1.0.0"
description = "GLFW support for Haze"
license = "MIT"
authors = ["HerrNamenlos123"]
type = "lib"

[generator.glfw-build]
exec = "scripts/build-glfw.hz"
inputs = []
outputs = [
    { module="this", dir="bin", path="include/GLFW/glfw3.h" },
    { module="this", dir="bin", path="include/GLFW/glfw3native.h" },
    # ... Output files ... (artifacts)
]

[interface.compiler.linux]
defines = ["_GLFW_X11", "_GLFW_WAYLAND"]

[interface.compiler.win32]
defines = ["_GLFW_WIN32"]

[linker]
flags = ["-lglfw3"]

[linker.linux]
flags = ["-lm", "-lGL", "-lpthread"]

[linker.win32]
flags = ["-luser32", "-lgdi32", "-lshell32"]